baseURL = 'http://www.sailaoda.cn/'
languageCode = "en-us"
title = "Sail's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "Sail Wu"
  homepage = "https://hackerwu.cn/"



[params]
mainSections = ["posts"]
headTitle = "Sail Wu"
disqus = "sailaoda" # disqus account name
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
[[params.socials]]
name = "About Me"
link = "https://hackerwu.cn/about/"
[[params.socials]]
name = "Github"
link = "https://github.com/sailaoda"
postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []

publishDir = docs